# Generated by Django 5.0.4 on 2024-07-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomanapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
