# Generated by Django 5.0.6 on 2024-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.TextField(default='Dr John', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.TextField(default='Teeth whitening', max_length=255),
        ),
    ]
